const paris = 35;
console.log(paris);
const isLogIn = true;
console.log(isLogIn);
const isLogOut = false;
console.log(isLogOut);
const emailAddress = "example.com";
console.log(emailAddress);
const basketBallGame = 90;
console.log(basketBallGame);
